// App 外壳及从旧入口迁出的页面样式；数值保持不变以避免视觉回归。
import { StyleSheet } from "react-native";
import { colors } from "../components/common";

export const appStyles = StyleSheet.create({
  appViewport: {
    flex: 1,
    backgroundColor: "#e9edf2",
    alignItems: "center",
    justifyContent: "center",
  },
  appShell: {
    flex: 1,
    width: "100%",
    backgroundColor: "white",
    overflow: "hidden",
  },
  desktopShell: {
    width: 430,
    minHeight: 844,
    maxHeight: 880,
    marginVertical: 16,
    borderRadius: 28,
    shadowColor: "#172033",
    shadowOpacity: 0.18,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  toast: {
    position: "absolute",
    left: "50%",
    bottom: 96,
    width: 150,
    marginLeft: -75,
    alignItems: "center",
    backgroundColor: "rgba(24,24,24,.9)",
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 10,
    zIndex: 1000,
    elevation: 20,
  },
  toastText: { color: "white", fontSize: 14, fontWeight: "600" },
  page: { flex: 1, backgroundColor: "white" },
  tabbar: {
    height: 74,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
    backgroundColor: "white",
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 7,
    paddingBottom: 6,
  },
  tab: { alignItems: "center", minWidth: 56, position: "relative" },
  tabIcon: { fontSize: 21, color: "#999" },
  tabText: { fontSize: 12, color: "#999", marginTop: 2 },
  tabActive: { color: "#171717", fontWeight: "700" },
  active: { color: colors.orange, fontWeight: "700" },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 7,
    backgroundColor: colors.orange,
    position: "absolute",
    right: 9,
    top: 0,
  },
  search: {
    height: 46,
    minWidth: 0,
    backgroundColor: "#f3f3f3",
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ai: { color: colors.orange, fontWeight: "900", fontStyle: "italic" },
  muted: { color: "#999", lineHeight: 22 },
  rankNo: { fontSize: 18, fontWeight: "800", color: "#e5a13c", width: 18 },
  meta: { color: "#999", fontSize: 13, marginTop: 6 },
  segment: {
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
  segmentOn: { fontWeight: "800", color: colors.orange },
  side: { width: 104, backgroundColor: "#f7f7f7" },
  sideItem: { paddingVertical: 22, alignItems: "center" },
  sideOn: {
    backgroundColor: "white",
    borderLeftWidth: 3,
    borderLeftColor: colors.orange,
  },
  tagGrid: {
    padding: 20,
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "flex-start",
  },
  filterTitle: {
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 14,
    width: "100%",
  },
  searchTop: {
    height: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
  },
  back: { fontSize: 34, lineHeight: 38 },
  searchAction: { color: colors.orange, fontWeight: "700" },
  resultTabs: {
    height: 50,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  wrap: { flexDirection: "row", flexWrap: "wrap" },
  titleRow: { flexDirection: "row", justifyContent: "space-between" },
  hot: { height: 50, flexDirection: "row", alignItems: "center", gap: 8 },
  empty: { padding: 40, textAlign: "center", color: "#999" },
  bookInfo: { flex: 1, minWidth: 0 },
  bookTitle: { fontSize: 16, fontWeight: "700", lineHeight: 22 },
  chat: { paddingHorizontal: 16 },
  aiHello: {
    backgroundColor: "#fff4ed",
    padding: 18,
    borderRadius: 18,
    marginVertical: 14,
  },
  aiTitle: { fontSize: 20, fontWeight: "800", marginBottom: 6 },
  bubble: {
    alignSelf: "flex-start",
    backgroundColor: "#f4f4f4",
    borderRadius: 16,
    padding: 14,
    maxWidth: "86%",
  },
  composer: {
    flexDirection: "row",
    padding: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: "#ddd",
    gap: 10,
  },
  composeInput: {
    flex: 1,
    minWidth: 0,
    backgroundColor: "#f4f4f4",
    borderRadius: 18,
    padding: 12,
    maxHeight: 100,
  },
  send: {
    backgroundColor: colors.orange,
    borderRadius: 18,
    paddingHorizontal: 18,
    justifyContent: "center",
  },
  heroTitle: { fontSize: 23, fontWeight: "900" },
  benefitCard: {
    marginVertical: 18,
    padding: 20,
    borderRadius: 24,
    backgroundColor: "#fff4e6",
  },
  coin: { fontSize: 31, fontWeight: "900", color: "#f0a236" },
  days: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 20,
  },
  day: {
    flex: 1,
    maxWidth: 40,
    height: 56,
    marginHorizontal: 2,
    borderRadius: 14,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
  dayOn: { backgroundColor: "#ffd9b8" },
  login: {
    backgroundColor: colors.orange,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
  },
  loginText: { color: "white", fontWeight: "800" },
  task: {
    height: 62,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
  shelfTabs: {
    height: 70,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  readTime: {
    marginHorizontal: 18,
    padding: 12,
    backgroundColor: "#f6f6f6",
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  banner: {
    margin: 18,
    padding: 16,
    borderRadius: 16,
    backgroundColor: "#f5f4df",
  },
  filterBar: { paddingLeft: 16, flexDirection: "row", alignItems: "center" },
  filterScroller: { flex: 1 },
  filterScrollerContent: { paddingRight: 6 },
  filterTrigger: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "white",
  },
  editTop: {
    height: 60,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  editTitle: {
    flex: 1,
    minWidth: 0,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "800",
  },
  actionBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 82,
    backgroundColor: "white",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: "#ddd",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  actionIcon: { fontSize: 24 },
  actionLabel: { fontSize: 11, marginTop: 4 },
  filterBlock: { padding: 20, borderBottomWidth: 8, borderColor: "#f7f7f7" },
  profileHead: {
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
    marginTop: 20,
  },
  profileIdentity: { flex: 1, minWidth: 0 },
  avatar: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#ffd5bd",
    alignItems: "center",
    justifyContent: "center",
  },
  stats: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 25,
  },
  statNo: { fontSize: 20, fontWeight: "800", textAlign: "center" },
  quick: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 18,
  },
  quickItem: { alignItems: "center", width: "20%", paddingHorizontal: 2 },
  quickIcon: { fontSize: 25, marginBottom: 7 },
  quickLabel: { fontSize: 12, textAlign: "center" },
  profileCard: { padding: 18, borderRadius: 18, backgroundColor: "#fafafa" },
  discussion: {
    padding: 16,
    borderRadius: 14,
    backgroundColor: "#f7f7f7",
    marginBottom: 18,
  },
  menuRow: {
    height: 52,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
  addShelf: { position: "absolute", right: 30, top: 25 },
  swipeDelete: { position: "absolute", right: 25, bottom: 22 },
  userHero: { backgroundColor: "#fde5d7", height: 310, alignItems: "center" },
  bigAvatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
  userName: { fontSize: 25, fontWeight: "900", margin: 12 },
  archive: {
    margin: 18,
    padding: 20,
    borderRadius: 20,
    backgroundColor: "#fafafa",
  },
  archiveStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
  },
  userBio: { marginTop: 18, color: "#777" },
  profileTabs: {
    height: 70,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
  creationCard: {
    width: "52%",
    margin: 16,
    padding: 10,
    borderRadius: 16,
    backgroundColor: "white",
  },
  creationPlaceholder: {
    height: 260,
    borderRadius: 14,
    backgroundColor: "#d7dde5",
    alignItems: "center",
    justifyContent: "center",
  },
  creationText: {
    fontSize: 25,
    fontWeight: "800",
    lineHeight: 40,
    textAlign: "center",
    padding: 20,
  },
  reader: { flex: 1 },
  readerTop: {
    height: 70,
    paddingHorizontal: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 2,
  },
  readerBody: { paddingHorizontal: 28, paddingTop: 30, paddingBottom: 180 },
  chapterTitle: { fontSize: 25, fontWeight: "900", marginBottom: 28 },
  paragraph: { marginBottom: 20 },
  readerBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 18,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(0,0,0,.12)",
  },
  chapterBar: { flexDirection: "row", alignItems: "center", gap: 14 },
  progress: {
    height: 30,
    flex: 1,
    justifyContent: "center",
    borderBottomWidth: 5,
    borderColor: "rgba(128,128,128,.2)",
  },
  progressDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "white",
    position: "absolute",
    left: "30%",
  },
  readerActions: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 20,
  },
  readerAction: { textAlign: "center", lineHeight: 25 },
  listen: {
    position: "absolute",
    right: 18,
    bottom: 190,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#665f58",
    alignItems: "center",
    justifyContent: "center",
  },
  noteScrim: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  noteMenu: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 14,
    gap: 14,
  },
  panelScrim: { flex: 1, backgroundColor: "rgba(0,0,0,.2)" },
  readerPanel: {
    height: "58%",
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: "white",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 22,
  },
  panelTabs: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 24,
  },
  panelTab: { fontSize: 18, fontWeight: "700" },
  auto: {
    textAlign: "center",
    color: colors.orange,
    fontWeight: "800",
    padding: 12,
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  sizeBtn: { fontSize: 24, padding: 10 },
  palette: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 26,
  },
  swatch: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  swatchOn: { borderWidth: 3, borderColor: colors.orange },
  review: {
    paddingVertical: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
    lineHeight: 23,
  },
  chapterRow: {
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "#eee",
  },
});
