export const books = [
  {
    id: "b1",
    title: "缺德师妹一出手，九州大佬全麻了",
    author: "月下执灯",
    cover: "九州\n大佬",
    tags: ["玄幻言情", "古代言情", "穿越", "团宠"],
    score: 9.1,
    status: "连载中",
    chapter: "第329章 在路上",
    unread: 78,
    description: "陆灵悠穿成一本团宠万人迷书中的炮灰女配。她不按套路出牌，靠一身本事闯遍九州。",
  },
  {
    id: "b2",
    title: "机甲小队，但全员邪修",
    author: "一梦惊鸿",
    cover: "机甲\n小队",
    tags: ["科幻末世", "机甲", "群像"],
    score: 8.9,
    status: "连载中",
    chapter: "第658章 旺财的口水",
    unread: 40,
    description: "一支画风清奇的机甲小队，在末世中踏上拯救世界的旅程。",
  },
  {
    id: "b3",
    title: "盗墓：你是个女孩子啊！",
    author: "四月一日",
    cover: "盗墓\n日常",
    tags: ["悬疑", "盗墓", "女强"],
    score: 8.7,
    status: "连载中",
    chapter: "第901章 汪尹日常2",
    unread: 693,
    description: "她意外加入神秘探险队，古墓背后的秘密逐渐浮出水面。",
  },
  {
    id: "b4",
    title: "首席不懂演戏，但她略通一些术法",
    author: "烤苕皮来喽",
    cover: "首席\n术法",
    tags: ["现代言情", "娱乐圈", "玄学"],
    score: 9,
    status: "已完结",
    chapter: "第533章 大结局·下",
    unread: 350,
    description: "玄门首席误入娱乐圈，不会演戏，却能让所有灵异现场当场安静。",
  },
  {
    id: "b5",
    title: "末日灾祸：谁让这群癫子去救世的",
    author: "长川",
    cover: "末日\n灾祸",
    tags: ["末世", "群像", "脑洞"],
    score: 9.3,
    status: "已完结",
    chapter: "番外五 初始之地",
    unread: 0,
    description: "看似不靠谱的伙伴们，被迫接下了救世任务。",
  },
];
export const chapters = books.flatMap((b, bi) =>
  Array.from({ length: 5 }, (_, i) => ({
    id: `c${bi + 1}-${i + 1}`,
    book_id: b.id,
    chapter_number: i + 1,
    title: `第 ${i + 1} 章 ${i ? "新的旅途" : "故事开始"}`,
    content_json: [
      { p_id: "p1", text: "暮色从远山缓缓落下，故事在这一刻开始。" },
      { p_id: "p2", text: "所有人都明白，前方的道路不会平坦。" },
      { p_id: "p3", text: "但他们仍然选择并肩向前。" },
    ],
    updated_at: new Date().toISOString(),
  })),
);
